"""Render the architecture map and the module index. Pure functions: no I/O."""
from __future__ import annotations

from . import FORMAT_VERSION
from .config import Config
from .facts import Facts
from .graph import compute_depths, find_cycles, find_duplicate_names, importers, library_modules
from .scan import Module

CAP_PACKAGES = 25
CAP_HUBS = 25
CAP_TABLES = 25
CAP_ROUTE_GROUPS = 25
CAP_ROUTE_FILES = 25
CAP_CYCLES = 10
CAP_DUPLICATES = 20
NAMES_PER_DEPTH = 6
NAMES_PER_CYCLE = 8
WRITERS_NAMED = 4
READERS_NAMED = 4
TITLE_WIDTH = 70
INDEX_TITLE_WIDTH = 90
NONE_FOUND = "None found by this detector."


def _plural(n: int, word: str, many: str | None = None) -> str:
    return f"{n} {word}" if n == 1 else f"{n} {many or word + 's'}"


def _names(keys, limit: int) -> str:
    keys = list(keys)
    shown = ", ".join(f"`{k}`" for k in keys[:limit])
    return shown + (f", +{len(keys) - limit}" if len(keys) > limit else "")


def _title(mod: Module) -> str:
    return mod.doc.strip()[:TITLE_WIDTH]


def _route_detector(cfg: Config) -> str:
    listed = ", ".join(f"`.{d}(...)`" for d in cfg.route_decorators) or "nothing (no decorators are configured)"
    return f"Detector: functions decorated with {listed} whose first argument is a string literal starting with `/`."


def _sql_detector(cfg: Config) -> str:
    if cfg.sql.is_default:
        return (
            "Detector: `CREATE TABLE` statements (including `CREATE VIRTUAL TABLE`) found in string literals; temporary "
            "tables and schema-qualified names are not counted. Uses and writes are matched against those names."
        )
    return (
        "Detector: custom SQL patterns from the configuration; uses and writes are matched against the names they find."
    )


def render_architecture(mods: dict[str, Module], facts: Facts, cfg: Config, excluded: int) -> str:
    real = sorted((m for m in mods.values() if not m.is_test), key=lambda m: m.key)
    n_tests = sum(1 for m in mods.values() if m.is_test)
    n_unparsed = sum(1 for m in mods.values() if m.parse_error)
    imp = importers(mods)
    library = library_modules(mods)
    packages: dict[str | None, list[str]] = {}
    for m in real:
        packages.setdefault(m.key.split(".")[0] if "." in m.key else None, []).append(m.key)
    named = {k: v for k, v in packages.items() if k is not None}
    n_routes = sum(len(v) for v in facts.routes.values())

    out = [
        f"# Architecture map: {cfg.title}" if cfg.title else "# Architecture map",
        "",
        f"Generated by indextool {FORMAT_VERSION} from the source code. Everything below is read from the source and "
        "regenerated, never edited by hand, so it cannot go stale and needs no upkeep.",
        "",
        "## In numbers",
        f"- {_plural(len(real), 'module')} (plus {_plural(n_tests, 'test module')}) in {_plural(len(named), 'package')}; "
        f"{sum(1 for m in real if m.has_main)} with a `__main__` guard",
        f"- {len(library)} {'is' if len(library) == 1 else 'are'} imported by another module; "
        f"{len(real) - len(library)} standalone (imported by nothing: scripts, servers, entry points)",
        f"- {_plural(n_routes, 'route')} in {_plural(len(facts.routes), 'file')}; "
        f"{_plural(len(facts.created), 'table')} created in code",
    ]
    if cfg.exclude.patterns:
        out.append(f"- {_plural(excluded, 'file')} excluded by the configured `exclude` patterns")
    if n_unparsed:
        out.append(
            f"- {_plural(n_unparsed, 'file')} could not be parsed "
            f"(counted as {'a module' if n_unparsed == 1 else 'modules'} with no imports)"
        )
    out.append("")

    out.append("## Packages")
    ranked_packages = sorted(named.items())
    out += [f"- `{name}` - {_plural(len(keys), 'module')}" for name, keys in ranked_packages[:CAP_PACKAGES]]
    if len(ranked_packages) > CAP_PACKAGES:
        out.append(f"- (+{len(ranked_packages) - CAP_PACKAGES} more packages)")
    out.append(f"- top level - {_plural(len(packages.get(None, [])), 'module')}")
    out.append("")

    depths = compute_depths(mods)
    levels: dict[int, list[str]] = {}
    for key in library:
        levels.setdefault(depths[key], []).append(key)
    out += [
        "## Dependency layers (computed from imports)",
        "Library modules only. Depth 0 imports no other module here; depth N is one more than the deepest module it "
        "imports; modules in an import cycle share a depth. The most imported modules at each depth:",
    ]
    for depth in sorted(levels):
        members = sorted(levels[depth], key=lambda k: (-len(imp[k]), k))
        out.append(f"- depth {depth} ({_plural(len(members), 'module')}): " + _names(members, NAMES_PER_DEPTH))
    out.append("")

    cycles = [[k for k in comp if not mods[k].is_test] for comp in find_cycles(mods)]
    cycles = [c for c in cycles if len(c) > 1]
    out.append("## Import cycles")
    if cycles:
        out.append("Modules that import each other, directly or through others; change them together.")
        out += [f"- {_names(c, NAMES_PER_CYCLE)} ({_plural(len(c), 'module')})" for c in cycles[:CAP_CYCLES]]
        if len(cycles) > CAP_CYCLES:
            out.append(f"- (+{len(cycles) - CAP_CYCLES} more cycles)")
    else:
        out.append("None.")
    out.append("")

    hubs = sorted((m for m in real if imp[m.key]), key=lambda m: (-len(imp[m.key]), m.key))
    out.append("## Most depended-on modules")
    for m in hubs[:CAP_HUBS]:
        out.append(f"- `{m.key}` ({_plural(len(imp[m.key]), 'importer')})" + (f" - {_title(m)}" if m.doc.strip() else ""))
    if len(hubs) > CAP_HUBS:
        out.append(f"- (+{len(hubs) - CAP_HUBS} more)")
    out.append("")

    out += ["## HTTP surface", _route_detector(cfg)]
    if n_routes:
        route_files = sorted(facts.routes.items())
        shown = ", ".join(f"`{k}` ({len(v)})" for k, v in route_files[:CAP_ROUTE_FILES])
        if len(route_files) > CAP_ROUTE_FILES:
            shown += f", +{len(route_files) - CAP_ROUTE_FILES}"
        out.append(f"{_plural(n_routes, 'route')} in {_plural(len(route_files), 'file')}: {shown}.")
        groups: dict[str, int] = {}
        for paths in facts.routes.values():
            for path in paths:
                prefix = "/" + "/".join(path.strip("/").split("/")[:3])
                groups[prefix] = groups.get(prefix, 0) + 1
        ranked = sorted(groups.items(), key=lambda kv: (-kv[1], kv[0]))
        out += [f"- `{prefix}` - {_plural(n, 'route')}" for prefix, n in ranked[:CAP_ROUTE_GROUPS]]
        if len(ranked) > CAP_ROUTE_GROUPS:
            out.append(f"- (+{len(ranked) - CAP_ROUTE_GROUPS} more route groups)")
    else:
        out.append(NONE_FOUND)
    out.append("")

    out += ["## Database", _sql_detector(cfg)]
    if facts.created:
        out.append(
            f"{_plural(len(facts.created), 'table')} created in code (tables that exist only in the database file are not "
            "counted). Ranked by how many library modules use them; standalone scripts are counted but named last:"
        )

        def by_role(keys):
            return sorted(keys, key=lambda k: (k not in library, -len(imp.get(k, ())), k))

        ranked_tables = sorted(
            facts.tables.items(),
            key=lambda kv: (-len([k for k in kv[1] if k in library]), -len(kv[1]), kv[0]),
        )
        for name, keys in ranked_tables[:CAP_TABLES]:
            writers = facts.writers.get(name, set())
            line = (
                f"- `{name}` - {_plural(len(keys), 'module')} ({len([k for k in keys if k in library])} library, "
                f"{len([k for k in keys if k not in library])} standalone)"
            )
            if writers:
                line += "; written by " + _names(by_role(writers), WRITERS_NAMED)
            readers = [k for k in by_role(keys - writers) if k in library]
            if readers:
                line += "; also used by " + _names(readers, READERS_NAMED)
            out.append(line)
        if len(ranked_tables) > CAP_TABLES:
            out.append(f"- (+{len(ranked_tables) - CAP_TABLES} more tables)")
    else:
        out.append(NONE_FOUND)
    out.append("")

    same = find_duplicate_names(mods)
    if same:
        out += [
            "## Same name, different modules",
            "Defined in two or more library modules. Check which one a piece of code really imports before you edit or "
            "cite it.",
        ]
        out += [f"- {kind} `{name}`: {_names(keys, NAMES_PER_CYCLE)}" for kind, name, keys in same[:CAP_DUPLICATES]]
        if len(same) > CAP_DUPLICATES:
            out.append(f"- (+{len(same) - CAP_DUPLICATES} more)")
        out.append("")

    decorators = ", ".join(f"`{d}`" for d in cfg.route_decorators) or "(none configured)"
    out += [
        "## What this map cannot say",
        "- Why a module exists or how modules cooperate beyond importing each other: titles are the first line of each "
        "docstring.",
        "- Formulas, thresholds, ordering of the data flow, and the reasons behind design rules.",
        "- Imports made through `importlib`, `exec` or `sys.path` changes, and anything outside Python source files.",
        "- Tables that no `CREATE TABLE` statement in a string literal creates (created outside the code, by an ORM, or "
        "under a name built at run time).",
        f"- Routes not registered by a decorator named {decorators} with a literal path starting with `/`.",
    ]
    return "\n".join(out)


def render_index(mods: dict[str, Module], facts: Facts, cfg: Config) -> str:
    library = library_modules(mods)
    per_module: dict[str, list[str]] = {}
    for table, keys in facts.tables.items():
        for key in keys:
            per_module.setdefault(key, []).append(table)
    lines = [
        f"# indextool {FORMAT_VERSION} index, one line per module, fields split by a pipe: key, first docstring line, "
        "role, tables, routes. Role: `lib` (another module imports it) or `standalone` (nothing does), then the io the "
        "code shows. Tables ending in * are ones the module writes."
    ]
    for m in sorted((m for m in mods.values() if not m.is_test), key=lambda m: m.key):
        role = " ".join(p for p in ("lib" if m.key in library else "standalone", facts.io.get(m.key, "")) if p)
        cells = [m.key, m.doc.strip()[:INDEX_TITLE_WIDTH] or "-", role]
        tables = sorted(per_module.get(m.key, []))
        if tables:
            cells.append(
                "tables: " + ", ".join(t + ("*" if m.key in facts.writers.get(t, ()) else "") for t in tables)
            )
        if facts.routes.get(m.key):
            cells.append(f"routes {len(facts.routes[m.key])}")
        lines.append(" | ".join(cells))
    return "\n".join(lines)
