import importlib.util
from pathlib import Path

import pytest

from tests.helpers import commit_all, git, make_repo


def load():
    path = Path(__file__).resolve().parent.parent / "scripts" / "check_patch_release.py"
    spec = importlib.util.spec_from_file_location("check_patch_release", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_parse_tag():
    m = load()
    assert m.parse_tag("v1.22.3") == (1, 22, 3)
    for bad in ("1.2.3", "v1.2", "v1.2.3rc1", "release-1"):
        with pytest.raises(ValueError):
            m.parse_tag(bad)


def make_project(tmp_path, version, golden):
    return make_repo(
        tmp_path,
        {
            "src/indextool/__init__.py": f'__version__ = "{version}"\n',
            "tests/golden/g.md": golden,
        },
    )


def test_declared_version_and_tag_mismatch_is_an_error(tmp_path, monkeypatch):
    m = load()
    repo = make_project(tmp_path, "0.1.0", "Generated by indextool 0.1\nbody\n")
    monkeypatch.chdir(repo)
    assert m.declared_version(repo) == "0.1.0"
    assert m.main(["check", "v0.2.0"]) == 2
    assert m.main(["check", "nonsense"]) == 2
    assert m.main(["check", "v0.1.0"]) == 0


def test_a_patch_release_must_not_change_the_goldens(tmp_path, monkeypatch):
    m = load()
    repo = make_project(tmp_path, "0.1.0", "Generated by indextool 0.1\nbody\n")
    git(repo, "tag", "v0.1.0")
    (repo / "src" / "indextool" / "__init__.py").write_text('__version__ = "0.1.1"\n', encoding="utf-8")
    commit_all(repo, "patch")
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 0
    (repo / "tests" / "golden" / "g.md").write_text("Generated by indextool 0.1\nchanged\n", encoding="utf-8")
    commit_all(repo, "output changed in a patch")
    assert m.main(["check", "v0.1.1"]) == 1
