import importlib.util
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load():
    spec = importlib.util.spec_from_file_location("parity", ROOT / "scripts" / "parity.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


REFERENCE_MAP = "\n".join(
    [
        "# Architecture skeleton: some_folder",
        "",
        "Derived from the code by a generator.",
        "",
        "## In numbers",
        "- 3 modules",
        "",
        "## HTTP surface",
        "2 routes in 1 file: `web` (2).",
        "",
        "## What this skeleton does not say",
        "- reasons",
    ]
)
OUR_MAP = "\n".join(
    [
        "# Architecture map",
        "",
        "Generated by indextool 0.1 from the source code.",
        "",
        "## In numbers",
        "- 3 modules",
        "- 4 files excluded by the configured `exclude` patterns",
        "- 1 file could not be parsed (counted as a module with no imports)",
        "",
        "## HTTP surface",
        "Detector: functions decorated with `.route(...)`.",
        "2 routes in 1 file: `web` (2).",
        "",
        "## What this map cannot say",
        "- other reasons",
    ]
)


def test_allowed_categories_are_ignored():
    m = load()
    assert m.reduce("map", REFERENCE_MAP) == m.reduce("map", OUR_MAP)


def test_a_real_difference_is_flagged(tmp_path, capsys):
    m = load()
    expected = tmp_path / "expected.md"
    actual = tmp_path / "actual.md"
    expected.write_text(REFERENCE_MAP, encoding="utf-8")
    actual.write_text(OUR_MAP.replace("- 3 modules", "- 4 modules"), encoding="utf-8")
    assert m.main(["parity", "map", str(expected), str(actual)]) == 1
    assert "4 modules" in capsys.readouterr().out
    actual.write_text(OUR_MAP, encoding="utf-8")
    assert m.main(["parity", "map", str(expected), str(actual)]) == 0


def test_index_kind_ignores_only_the_first_line():
    m = load()
    assert m.reduce("index", "# header one\na | x | lib\nb | y | standalone") == m.reduce(
        "index", "# other header\na | x | lib\nb | y | standalone"
    )
    assert m.reduce("index", "# h\na | x | lib") != m.reduce("index", "# h\na | x | standalone")


def test_bad_usage_is_exit_code_2():
    assert load().main(["parity", "map", "only-one-file"]) == 2
