import importlib.util
from pathlib import Path

from tests.helpers import commit_all, git


def load():
    path = Path(__file__).resolve().parent.parent / "scripts" / "check_golden_bump.py"
    spec = importlib.util.spec_from_file_location("check_golden_bump", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


OLD = "# Map\n\nGenerated by indextool 0.1 from the source.\nbody\n"


def test_bump_required_only_when_the_body_changed_under_the_same_version():
    m = load()
    assert m.bump_required(OLD, OLD) is False
    assert m.bump_required(OLD, OLD.replace("body", "other")) is True
    assert m.bump_required(OLD, OLD.replace("0.1", "0.2").replace("body", "other")) is False
    assert m.header_version("no version here") is None


def test_main_flags_an_unbumped_golden_change_and_accepts_a_bumped_one(repo_factory, monkeypatch, capsys):
    m = load()
    repo = repo_factory({"tests/golden/g.md": OLD})
    git(repo, "checkout", "-q", "-b", "feature")
    golden = repo / "tests" / "golden" / "g.md"
    golden.write_text(OLD.replace("body", "changed"), encoding="utf-8")
    commit_all(repo, "change without a bump")
    monkeypatch.chdir(repo)
    assert m.main(["check", "main"]) == 1
    assert "tests/golden/g.md" in capsys.readouterr().out
    golden.write_text(OLD.replace("0.1", "0.2").replace("body", "changed"), encoding="utf-8")
    commit_all(repo, "bump")
    assert m.main(["check", "main"]) == 0


def test_main_needs_a_base_ref():
    assert load().main(["check"]) == 2
