import importlib.util
from pathlib import Path

import pytest

from tests.helpers import commit_all, git, make_repo


def load():
    path = Path(__file__).resolve().parent.parent / "scripts" / "check_patch_release.py"
    spec = importlib.util.spec_from_file_location("check_patch_release", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_parse_tag():
    m = load()
    assert m.parse_tag("v1.22.3") == (1, 22, 3)
    for bad in ("1.2.3", "v1.2", "v1.2.3rc1", "release-1"):
        with pytest.raises(ValueError):
            m.parse_tag(bad)


def make_project(tmp_path, version, golden):
    return make_repo(
        tmp_path,
        {
            "src/indextool/__init__.py": f'__version__ = "{version}"\n',
            "tests/golden/g.md": golden,
        },
    )


def test_declared_version_and_tag_mismatch_is_an_error(tmp_path, monkeypatch):
    m = load()
    repo = make_project(tmp_path, "0.1.0", "Generated by indextool 0.1\nbody\n")
    monkeypatch.chdir(repo)
    assert m.declared_version(str(repo), "HEAD") == "0.1.0"
    assert m.main(["check", "v0.2.0"]) == 2
    assert m.main(["check", "nonsense"]) == 2
    assert m.main(["check", "v0.1.0"]) == 0


def test_a_patch_release_must_not_change_the_goldens(tmp_path, monkeypatch):
    m = load()
    repo = make_project(tmp_path, "0.1.0", "Generated by indextool 0.1\nbody\n")
    git(repo, "tag", "v0.1.0")
    (repo / "src" / "indextool" / "__init__.py").write_text('__version__ = "0.1.1"\n', encoding="utf-8")
    commit_all(repo, "patch")
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 0
    (repo / "tests" / "golden" / "g.md").write_text("Generated by indextool 0.1\nchanged\n", encoding="utf-8")
    commit_all(repo, "output changed in a patch")
    assert m.main(["check", "v0.1.1"]) == 1


GOLDEN = "Generated by indextool 0.1\nbody\n"
CHANGED = "Generated by indextool 0.1\nchanged\n"


def put(repo, rel, content):
    """Write bytes exactly (Path.write_text would write CRLF on Windows)."""
    path = repo / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content if isinstance(content, bytes) else content.encode("utf-8"))
    return path


def released_project(tmp_path, golden=GOLDEN):
    """A repository tagged v0.1.0 whose HEAD is a committed 0.1.1 patch with the golden untouched."""
    repo = make_project(tmp_path, "0.1.0", golden)
    git(repo, "tag", "v0.1.0")
    put(repo, "src/indextool/__init__.py", '__version__ = "0.1.1"\n')
    commit_all(repo, "patch")
    return repo


def test_a_base_without_goldens_is_exit_2_not_a_pass(tmp_path, monkeypatch, capsys):
    m = load()
    repo = make_repo(tmp_path, {"src/indextool/__init__.py": '__version__ = "0.1.0"\n', "README.md": "hi\n"})
    git(repo, "tag", "v0.1.0")
    put(repo, "src/indextool/__init__.py", '__version__ = "0.1.1"\n')
    put(repo, "tests/golden/g.md", GOLDEN)
    commit_all(repo, "patch that adds goldens the base never had")
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 2
    captured = capsys.readouterr()
    assert captured.out == ""
    assert len(captured.err.strip().split("\n")) == 1 and "v0.1.0" in captured.err


def test_uncommitted_edits_to_a_golden_do_not_count(tmp_path, monkeypatch):
    m = load()
    repo = released_project(tmp_path)
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 0
    put(repo, "tests/golden/g.md", "Generated by indextool 0.1\nedited but not committed\n")
    assert m.main(["check", "v0.1.1"]) == 0


def test_a_committed_golden_change_is_found_even_if_the_working_tree_was_restored(tmp_path, monkeypatch):
    m = load()
    repo = released_project(tmp_path)
    put(repo, "tests/golden/g.md", CHANGED)
    commit_all(repo, "output changed in a patch")
    put(repo, "tests/golden/g.md", GOLDEN)  # the working tree looks like the base again; HEAD does not
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 1


def test_an_uncommitted_version_edit_does_not_count(tmp_path, monkeypatch):
    m = load()
    repo = released_project(tmp_path)
    put(repo, "src/indextool/__init__.py", '__version__ = "0.1.9"\n')
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 0
    assert m.main(["check", "v0.1.9"]) == 2


def test_the_tag_commit_is_judged_not_whatever_was_committed_after_it(tmp_path, monkeypatch):
    m = load()
    repo = released_project(tmp_path)
    git(repo, "tag", "-a", "v0.1.1", "-m", "release")  # an annotated tag must be peeled to its commit
    put(repo, "tests/golden/g.md", "Generated by indextool 0.1\nchanged after the tag\n")
    commit_all(repo, "later work on the branch")
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 0


def test_a_missing_base_tag_is_exit_2_with_one_line_naming_it(tmp_path, monkeypatch, capsys):
    m = load()
    repo = make_project(tmp_path, "0.1.1", GOLDEN)  # no v0.1.0 tag, as in a shallow or tagless checkout
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 2
    captured = capsys.readouterr()
    assert captured.out == ""
    lines = captured.err.strip().split("\n")
    assert len(lines) == 1 and "v0.1.0" in lines[0] and "fetch-depth: 0" in lines[0]


def test_the_gate_gives_the_same_answer_from_a_subdirectory(tmp_path, monkeypatch, capsys):
    m = load()
    repo = released_project(tmp_path)
    subdirectories = (repo / "tests", repo / "tests" / "golden", repo / "src" / "indextool")
    for directory in subdirectories:
        monkeypatch.chdir(directory)
        assert m.main(["check", "v0.1.1"]) == 0
    put(repo, "tests/golden/g.md", CHANGED)
    commit_all(repo, "output changed in a patch")
    capsys.readouterr()
    for directory in subdirectories:
        monkeypatch.chdir(directory)
        assert m.main(["check", "v0.1.1"]) == 1
        assert "tests/golden/g.md" in capsys.readouterr().out


def test_a_golden_deleted_since_the_base_counts_as_changed(tmp_path, monkeypatch, capsys):
    m = load()
    repo = released_project(tmp_path)
    (repo / "tests" / "golden" / "g.md").unlink()
    commit_all(repo, "golden removed in a patch")
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 1
    assert "tests/golden/g.md" in capsys.readouterr().out


def test_a_golden_added_since_the_base_is_ignored(tmp_path, monkeypatch):
    m = load()
    repo = released_project(tmp_path)
    put(repo, "tests/golden/new.md", "Generated by indextool 0.1\nnew\n")
    commit_all(repo, "a new golden")
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 0


def test_line_ending_only_differences_are_not_changes(tmp_path, monkeypatch):
    m = load()
    repo = released_project(tmp_path)
    put(repo, "tests/golden/g.md", GOLDEN.replace("\n", "\r\n"))
    commit_all(repo, "the golden checked in with CRLF")
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 0


def test_a_lone_carriage_return_in_an_unchanged_golden_is_not_a_change(tmp_path, monkeypatch):
    m = load()
    repo = released_project(tmp_path, golden=b"Generated by indextool 0.1\nbody\rwith a lone CR\n")
    monkeypatch.chdir(repo)
    assert m.main(["check", "v0.1.1"]) == 0


def test_a_bad_invocation_is_exit_2_with_one_line(tmp_path, monkeypatch, capsys):
    m = load()
    assert m.main(["check"]) == 2
    plain = tmp_path / "plain"
    plain.mkdir()
    monkeypatch.chdir(plain)
    capsys.readouterr()
    assert m.main(["check", "v0.1.1"]) == 2  # not a git repository
    captured = capsys.readouterr()
    assert captured.out == "" and len(captured.err.strip().split("\n")) == 1
